-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 14:33:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- #####################################
-- ALUNOS:
-- Adrian Raul
-- Alessando Lopes
-- Guilherme Silva

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agaa_questoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agaa_questoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agaa_questoes` DEFAULT CHARACTER SET utf8mb3 ;
USE `agaa_questoes` ;

-- -----------------------------------------------------
-- Table `agaa_questoes`.`prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`prova` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `codigo_prova` VARCHAR(30) NOT NULL,
  `fase` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `ano` SMALLINT NOT NULL,
  `dia` VARCHAR(20) NULL DEFAULT NULL,
  `data_aplicacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_prova_unica` (`ano` ASC, `codigo_prova` ASC, `fase` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agaa_questoes`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`questao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prova_id` BIGINT NOT NULL,
  `numero_na_prova` INT NOT NULL,
  `tipo` ENUM('OBJETIVA', 'DISCURSIVA') NOT NULL,
  `area_conhecimento` VARCHAR(80) NOT NULL,
  `disciplina` VARCHAR(80) NOT NULL,
  `assunto` VARCHAR(120) NOT NULL,
  `enunciado` TEXT NOT NULL,
  `dificuldade` ENUM('FACIL', 'MEDIO', 'DIFICIL') NOT NULL,
  `imagem_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_questao_prova` (`prova_id` ASC, `numero_na_prova` ASC) VISIBLE,
  CONSTRAINT `fk_questao_prova`
    FOREIGN KEY (`prova_id`)
    REFERENCES `agaa_questoes`.`prova` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agaa_questoes`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`alternativa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `questao_id` BIGINT NOT NULL,
  `letra` CHAR(1) NOT NULL,
  `texto` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alternativa_questao` (`questao_id` ASC) VISIBLE,
  CONSTRAINT `fk_alternativa_questao`
    FOREIGN KEY (`questao_id`)
    REFERENCES `agaa_questoes`.`questao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agaa_questoes`.`gabarito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`gabarito` (
  `questao_id` BIGINT NOT NULL,
  `alternativa_id` BIGINT NULL DEFAULT NULL,
  `res_esperada` TEXT NULL DEFAULT NULL,
  `fonte_oficial` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`questao_id`),
  INDEX `fk_gabarito_alternativa` (`alternativa_id` ASC) VISIBLE,
  CONSTRAINT `fk_gabarito_alternativa`
    FOREIGN KEY (`alternativa_id`)
    REFERENCES `agaa_questoes`.`alternativa` (`id`),
  CONSTRAINT `fk_gabarito_questao`
    FOREIGN KEY (`questao_id`)
    REFERENCES `agaa_questoes`.`questao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agaa_questoes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil` ENUM('ADMINISTRADOR', 'USUARIO') NOT NULL DEFAULT 'USUARIO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_email_unico` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agaa_questoes`.`simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`simulado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quantidade_questoes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_simulado_usuario` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_simulado_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agaa_questoes`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agaa_questoes`.`simulado_questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agaa_questoes`.`simulado_questao` (
  `simulado_id` BIGINT NOT NULL,
  `questao_id` BIGINT NOT NULL,
  PRIMARY KEY (`simulado_id`, `questao_id`),
  INDEX `fk_sq_questao` (`questao_id` ASC) VISIBLE,
  CONSTRAINT `fk_sq_questao`
    FOREIGN KEY (`questao_id`)
    REFERENCES `agaa_questoes`.`questao` (`id`),
  CONSTRAINT `fk_sq_simulado`
    FOREIGN KEY (`simulado_id`)
    REFERENCES `agaa_questoes`.`simulado` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
